# You can change this base image to anything else
# But make sure to use the correct version of Java
FROM adoptopenjdk/openjdk11:alpine-jre




WORKDIR /opt/app

COPY /var/lib/jenkins/workspace/ultimate-demo/java-maven-sonar-argocd-helm-k8s/spring-boot-app/target/spring-boot-web.jar app.jar

# This should not be changed
ENTRYPOINT ["java","-jar","app.jar"]
